### ISSUE TITLE
Errors out when playing as Vulpera (and probably Mechagnomes)

### ISSUE THREAD

**Issue by berwyn** [LudiusMaximus/CameraOverShoulderFix#24]
`cosFix:GetCurrentModelId()` depends on either `self.db.char.lastModelId` not being `nil`, or the player's race/gender existing in the table defined in `factors_races.lua`.

As of right now, Vulpera and Mechagnomes don't appear there, and as such the addon errors every time the code runs. I copied the values from the gnomes and it seems to be fine to me -- would you be interested in receiving a PR with those changes?

**Comment by LudiusMaximus** [comment]
Yes please! I have not had time to add these most recent Allied races. But Mechagnomes should be there. Are you sure this has been giving you an error as well?

**Comment by LudiusMaximus** [comment]
Never mind, I just did it. Thanks for your offer though! :-)

**Comment by berwyn** [comment]
Sorry, just now saw this! I hadn't tried with Mechagnomes to be honest, I haven't bothered to unlock them yet, but I didn't see them in the copy I have based on the master branch. That said, I might be out of date!
