### ISSUE TITLE
A bunch of mount offset data - how can I contribute?

### ISSUE THREAD

**Issue by Shushuda** [LudiusMaximus/CameraOverShoulderFix#26]
Hello again!

I've set a bunch of offsets for some mounts that had none. I have a rather big mount collection, so it's quite a few of them done now.

How can I send all that data to you, since the Export button is not yet implemented?

**Comment by LudiusMaximus** [comment]
That's great, thanks! Let's just wait until I have brought it all to a state for proper release. I will then also have implemented the "Export" button properly.
